#!/bin/sh

# SEQUENCE_TARGET is the region that should be FLANKED by primers
# SEQUENCE_TEMPLATE is the entire template
# SEQEUENCE_EXCLUDED_REGION is the region that should be excluded from primers (i.e. target in most cases)

# RUN SCRIPT WITH:
# /.getprimers.sh product_size target template excluded_region opt_size prim3_exe

seq=$3
opt_size=$5
prim3_exe=$6

$6 << EOF
SEQUENCE_ID=example
SEQUENCE_TEMPLATE=$seq
SEQUENCE_TARGET=$2
SEQUENCE_EXCLUDED_REGION=$4
PRIMER_TASK=pick_detection_primers
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_INTERNAL_OLIGO=0
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_MIN_GC=20.0
PRIMER_INTERNAL_MIN_GC=20.0
PRIMER_OPT_GC_PERCENT=50.0
PRIMER_MAX_GC=80.0
PRIMER_INTERNAL_MAX_GC=80.0
PRIMER_WT_GC_PERCENT_LT=0.0
PRIMER_INTERNAL_WT_GC_PERCENT_LT=0.0
PRIMER_WT_GC_PERCENT_GT=0.0
PRIMER_INTERNAL_WT_GC_PERCENT_GT=0.0
PRIMER_GC_CLAMP=0
PRIMER_MAX_END_GC=5
PRIMER_OPT_SIZE=25
PRIMER_MIN_SIZE=18
PRIMER_MAX_SIZE=25
PRIMER_MAX_NS_ACCEPTED=0
PRIMER_PRODUCT_SIZE_RANGE=$1
PRIMER_PRODUCT_OPT_SIZE=$opt_size
PRIMER_PAIR_WT_PRODUCT_SIZE_GT=0.1
PRIMER_PAIR_WT_PRODUCT_SIZE_LT=0.1
P3_FILE_FLAG=1
SEQUENCE_INTERNAL_EXCLUDED_REGION=37,21
PRIMER_EXPLAIN_FLAG=1
PRIMER_MIN_TM=57
PRIMER_MAX_TM=62
PRIMER_OPT_TM=60
PRIMER_PAIR_MAX_DIFF_TM=2
PRIMER_NUM_RETURN=200
PRIMER_MAX_HAIRPIN_TH=47
=
EOF
