language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  apt:
    packages:
    - primer3
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - flake8 --statistics tests prinia
  - py.test --cov=prinia --cov-report term-missing tests prinia