name: prinia
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bwa=0.7.17
  - libdeflate=1.0
  - primer3=2.4.1a
  - samtools=1.9
  - bzip2=1.0.6
  - ca-certificates=2018.8.24
  - certifi=2018.8.24
  - curl=7.61.0
  - krb5=1.14.6
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libssh2=1.8.0
  - libstdcxx-ng=7.2.0
  - ncurses=6.1
  - openssl=1.0.2p
  - perl=5.26.2
  - pip=18.0
  - python=3.5.5
  - readline=7.0
  - setuptools=40.4.0
  - sqlite=3.25.1
  - tk=8.6.8
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
